# Generated by Django 5.2.4 on 2025-08-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_category_description_recipe_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
