# Generated by Django 5.2.4 on 2025-08-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='serbing_unit',
            new_name='serving_unit',
        ),
    ]
